### PR TITLE
Fix formatting of changelog for emails and github releases

### PR DESCRIPTION
**Pull request by ChristopherAbram**

### CODE REVIEW

**Review by dmccloskey — COMMENTED** [review]
Looks fine to me.  Please ping me once the CI passes.

**Review by bertrandboudaud — COMMENTED** [review]
ok to me

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
"Retry DeepCode"

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by dmccloskey** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Pull request closed without merging**
