### PR TITLE
Fix formatting of changelog for emails and github releases

### PR DESCRIPTION
**Pull request by ChristopherAbram**

### CODE REVIEW

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
DeepCode issue...

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Review by dmccloskey — APPROVED** [review]
Looks good.  Use of the requirements list is a bit more elegant in my opinion.  @ahmedskhalil can you comment on what is going on with Deep Code?

**Comment by ghost** [comment]
Retry DeepCode

**Comment by ghost** [comment]
> Looks good. Use of the requirements list is a bit more elegant in my opinion. @ahmedskhalil can you comment on what is going on with Deep Code?

DeepCode need to have it's access permissions updated by smartpeak-ci, @ChristopherAbram could you take care of this?

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Comment by ChristopherAbram** [comment]
Retry DeepCode

**Pull request merged**
